baseURL = 'https://reztag.github.io/'
languageCode = 'en-us'
title = "Rez"
[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

# Enable emojis globally
enableEmoji = true

toc = false # set to false to disable table of contents 'globally'
tocOpen = false # set to true to open table of contents by default

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

#Adding menu buttons
[menu]
[[menu.main]]
  pageRef = "home"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef = "posts"
  name = 'Posts'
  url = '/posts/'
  weight = 20

[[menu.main]]
  pageRef = "resume"
  name = 'Resume'
  url = '/resume/'
  weight = 30

[[menu.main]]
  pageRef = "about"
  name = 'About'
  url = '/about/'
  weight = 40

[params]
  sitename = "Rez's blog"
  defaultColor = "auto" # set default color mode: dark or light
    # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
    # the default value is set to 'auto'.
    # You can take a look at layouts/index.html for more information.
  mainSections = ['posts'] # set the main sections of the site
  description = "Minimal Hugo blog theme with light and dark mode support"
  goToTop = true # set to false to disable 'go to top' button

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  background = "background.jpg" # put the file in assets folder
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "📒 Rez's Personal Blogsite"
  name = "Rez"
  description = "Finally set up! anyway I'm a CS student trying to get a foothold in binary digit machines."


[[params.socialIcons]]
name = "github"
url = "https://github.com/reztag"

[[params.socialIcons]]
name = "x"
url = "https://twitter.com/reztag"

[[params.socialIcons]]
name = "lastfm"
url = "https://last.fm/user/eechie"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"